exclude: ^(aws_service_for_third_part/sam-app/.aws-sam/|aws_service/.lambda_layers/).*\.py$
default_language_version:
  python: python3.9
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.14.0
  hooks:
    # Run the linter.
    - id: ruff-check
      types_or: [ python ]
      args:
        - fix
    # Run the formatter.
    - id: ruff-format
      types_or: [ python ]
