name: Build and Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  django-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  deploy-to-eb:
    needs: django-build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip"
      - name: Install EB CLI
        run: pip install awsebcli
      - name: Deploy to Elastic Beanstalk
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::218278578731:role/LabRole
          aws-region: us-east-1
      - name: deploy
        run: |
          cd backend
          eb init -r us-east-1 -p python-3.9 charging-sys
          eb create dev --service-role LabRole --instance_profile LabInstanceProfile
          eb deploy